server:
  port: 3000

spring:
  main:
    web-application-type: servlet
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
#    url: jdbc:h2:dcbmem:app
    driver-class-name: org.h2.Driver
    username: sa # ehstartupYS
    password: # ehsu61YS
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect


